### ISSUE TITLE
Una instancia nueva de SWBProcess crea sitio básico en lugar de sitio de procesos

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBP#19]
Incluir:

- [x]  Accesos
- [x]  Cache de recursos
- [x]  Memoria
- [x]  Pool de conexiones

- [x]  DBConsultas

- [x]  Filtros de administración
- [x]  Filtro de secciones

- [x]  Documentos del servidor 
- [x]  Plantillas
- [x]  Reglas
- [x]  Filtro de recursos
- [x]  Flujos de publicación
- [x]  Editor de plntillas XSLT

Quitar
- [x] Mapa de secciones 
- [x] DBNatural

**Comment by haxdai** [comment]
@jordivs Hay que usar el bundle

````sh
git clone --recursive https://github.com/SemanticWebBuilder/SWBPBundle.git
cd SWBPBundle
git submodule update --remote
git submodule foreach 'git checkout dev'
mvn package
````

**Comment by jordivs** [comment]
@haxdai use el bundle y se construye la instancia sin applets de SWBP, pero con el sitio Básico de portal

![captura](https://user-images.githubusercontent.com/7914633/28938690-72d4bffc-7854-11e7-97d2-ea646165a58c.PNG)

**Comment by haxdai** [comment]
El nombre de la plantilla de sitio que se carga por defecto al iniciar una nueva instancia de SWBPortal y SWBProcess cambió de "demo.zip" a "basico.zip". En SWBProcess el nombre de la plantilla es aún "demo.zip" por lo que no se estaba creando ese sitio.
