### ISSUE TITLE
Rutas no encontradas con una instancia levantada con contexto 

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBP#32]
**Características de la instancia**
SO: Centos 7
AS: Tomcat 9
DB: Hipersonic
JVM: 8
Ruta de instalación: /webapps/process/

**Sitio Web**
- [x] Imagen "SWBProcess Logo", direccionada a la ruta estática "/es/demo/home"
![captura](https://user-images.githubusercontent.com/7914633/29886761-da7d96ec-8d80-11e7-8875-85d06c2da4e0.PNG)

- [x]  Menú de la página home  "/swb/demo/TaskInbox"  y "/swb/demo/Monitor"
![captura](https://user-images.githubusercontent.com/7914633/29887182-39fd2c58-8d82-11e7-90f1-a704a197b605.PNG)

- [x] Icono de usuario firmado la manda a llamar desde src="/swbadmin/jsp/process/commons/css/images/usuario-3.png"
![captura](https://user-images.githubusercontent.com/7914633/29887343-b68cf8c0-8d82-11e7-8410-f9ea014de824.PNG)

- [x] FormsBuilderResource al ejecutar un proceso  ERROR - FormsBuilderResource - Error including render.jsp
javax.servlet.ServletException: File [/process/swbadmin/jsp/process/formsBuilder/render.jsp] not found
 
![captura](https://user-images.githubusercontent.com/7914633/29887531-5af4f926-8d83-11e7-8e87-6e6cf976f23b.PNG)

- [x] Contenido de la página Documentación, "SWBPUserDocumentation"
![captura](https://user-images.githubusercontent.com/7914633/29887951-bb72d7fe-8d84-11e7-88c1-a07b340a1ab1.PNG)

- [x] Al crear un directorio en Repositorio de documentos, se solicita la siguiente ruta "/frmprocess/canCreate?model=demo&clsid=swp:RepositoryDirectory"  se genera la ventana de error como se muestra en la imagen
![captura](https://user-images.githubusercontent.com/7914633/29888252-ede22022-8d85-11e7-9ca3-1809d3f67830.PNG)

**Comment by haxdai** [comment]
- [ ] Verificar rutas de inclusión de JSPs
- [ ] Verificar rutas de invocación de archivos js
- [ ] Cambiar imagen de usuario por icono de fontawesome
- [ ] Cambiar rutas fijas en HTMLContent de home
